- hosts: vps
  become: true
  roles:
    - { role: common, tags: common }
    - { role: caddy, tags: caddy }
    - { role: hedgedoc, tags: hedgedoc }
    - { role: grafana, tags: grafana }
    - { role: node_exporter, tags: node_exporter }
    - { role: prometheus, tags: prometheus, prometheus_config: "prometheus-vps.yml" }
    - role: geerlingguy.nodejs
      tags: nodejs
      vars:
        nodejs_version: "20.x"
    - { role: website, tags: website }

- hosts: site
  become: true
  roles:
    - { role: common, tags: common }
    - { role: prometheus, tags: prometheus, prometheus_config: "prometheus-site.yml" }
    - { role: node_exporter, tags: node_exporter }
    - { role: loki, tags: loki }

